repos:
-   repo: local
    hooks:
    - id: requirements
      name: requirements
      language: system
      entry: bash -C "venv/bin/pip3 freeze > requirements.txt"
      always_run: true
      pass_filenames: false
      stages: [commit]

   